---
- name: Instalar nfs-common
  package:
    name: nfs-common
    state: present
  when: inventory_hostname != 'nfs'

- name: Montar diret√≥rio NFS
  mount:
    src: "{{ hostvars['nfs']['ansible_host'] }}:/home/nfs/data"
    path: "/mnt/nfs"
    fstype: nfs
    state: mounted
  when: inventory_hostname != 'nfs'